### ISSUE TITLE
Multiple Targets?

### ISSUE THREAD

**Issue by JAD3N** [Permutatrix/rollup-stream#15]
Hi, I was hoping that I could use multiple targets with different formats but it doesn't seem to support it. Am I doing something wrong or is rollup-stream the incorrect tool for this?

**Comment by lemmabit** [comment]
Multiple targets can be done; this should be in the README, but look
through the previously closed issues on this repository and you can find
the one where I explained it. Sorry I can't find it for you right now.
Every configuration option can be varied between targets, so different
formats shouldn't be a problem. Just ask on this issue if you have any
troubles getting this working.

On Jul 28, 2017 15:45, "Jaden" <notifications@github.com> wrote:

Hi, I was hoping that I could use multiple targets with different formats
but it doesn't seem to support it. Am I doing something wrong or is
rollup-stream the incorrect tool for this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Permutatrix/rollup-stream/issues/15>, or mute the thread
