### ISSUE TITLE
Incorrect file content with merge-stream

### ISSUE THREAD

**Issue by adammockor** [Permutatrix/rollup-stream#6]
I am trying to use this with merge-stream for creating multiple bundles. 

``` js
var gulp = require('gulp');
var merge = require('merge-stream');
var rollup = require('rollup-stream');
var source = require('vinyl-source-stream');
var buffer = require('vinyl-buffer');

gulp.task('scripts', function () {

  var bundles = ['a.js', 'b.js'].map(function(src) {
    return rollup({entry: src})
      .on('error', handleError)
      .pipe(source(path.basename(src)))
      .pipe(buffer())
      .pipe(sourcemaps.init({loadMaps: true}))
      .pipe(sourcemaps.write('.')))
      .pipe(gulp.dest('./dest'));
  });

  return merge(bundles);
});
```

But problem is that all bundles ('a.js', 'b.js') has same content of 'a.js'.

**Comment by lemmabit** [comment]
I couldn't reproduce the bug as you represent it here, but this line from before you edited the issue (i.e. the version I saw in the email GitHub sent me) caught my interest:

``` js
config.scripts.rollupCfg.entry = src;
```

If you've been reusing the same options object every time you call rollup-stream, that would explain the problem, since rollup-stream wasn't actually reading the options object until the next tick&mdash;after you're already done adjusting it for each call.

In v1.11.0, rollup-stream now copies the options object when it's called and is guaranteed not to hold a reference to it after returning. See if your task works now.

**Comment by adammockor** [comment]
Thank you for quick fix! 💯 

It was indeed problem with reusing same config object, so path were wrongly set.
